# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# extends:
#   template: simple-template.yml
#   parameters:
#     yesNo: true

# trigger:
#   branches:
#     include:
#       - master
#       - release/*

# pool:
#   vmImage: ubuntu-latest
  
# steps:
#   - template: simple-template.yml



# jobs:
# - job: myAJob
#   pool:
#     vmImage: ubuntu-latest
  
#   steps:
#     - bash: echo "hello A"

# - job: myBJob
#   pool:
#     vmImage: ubuntu-latest
  
#   steps:
#     - bash: echo "hello B"



# stages:
# - stage: stageA
#   jobs:
#     - job: jobA
#       steps:
#         -  script: echo "stageA jobA"
#     - job: jobB
#       steps:
#         - script: echo "stageA jobB"

# - stage: stageB
#   jobs:
#     - job: jobA
#       steps:
#         - script: echo "stageB jobA"
#     - job: jobB
#       steps:
#         - script: echo "stageB jobB"



# jobs:
#   - job: Debug
#     steps:
#       - script: echo hello from the debug build
#   - job: Release
#     dependsOn: Debug
#     steps:
#       - script: echo hello from the release build



stages:
- stage: stageA
  jobs:
    - job: InitialA
      steps:
        -  script: echo "stageA InitialA"
    - job: InitialB
      steps:
        - script: echo "stageA InitialB"

- stage: stageB
  jobs:
    - job: Subsequent
      dependsOn:
        - InitialA
        - InitialB
      steps:
        - script: echo "stageB Subsequent"