# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - release/*

pool:
  vmImage: ubuntu-latest

parameters:
  - name: branch
    type: string
    default: feature/test

steps:
- script: echo Hello, ${{parameters.branch}}
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'