# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# extends:
#   template: simple-template.yml
#   parameters:
#     yesNo: true

# trigger:
#   branches:
#     include:
#       - master
#       - release/*

# pool:
#   vmImage: ubuntu-latest
  
# steps:
#   - template: simple-template.yml

parameters:
- name: yesNo # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false
  
variables:
  favoriteVeggie: 'brussels sprouts'

steps:
- script: echo ${{ parameters.yesNo }},${{ variables.favoriteVeggie }}
